name: ui_satnetcom_customer_services
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.3
  provider: ^6.1.1
  firebase_core: ^2.24.2 # Essential for all Firebase products
  cloud_firestore: ^4.13.6 # For your database
  firebase_auth: ^4.15.2 # For authentication
  firebase_messaging: ^14.7.9 # For notifications/pop-ups

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
