// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkLlnrYJKXzgZmQy7YFAp2zOfqj80fkrM',
    appId: '1:642030263409:web:192edc43d1dcebc7aacfd0',
    messagingSenderId: '642030263409',
    projectId: 'snc-customer-service',
    authDomain: 'snc-customer-service.firebaseapp.com',
    storageBucket: 'snc-customer-service.firebasestorage.app',
    measurementId: 'G-GGZ1T8QF99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQlPWSIm4YRBF0pdwTt81UBv7sOw4oMJA',
    appId: '1:642030263409:android:0afd64a0028a5327aacfd0',
    messagingSenderId: '642030263409',
    projectId: 'snc-customer-service',
    storageBucket: 'snc-customer-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpFwRFN-XYFo3b4tnUghqMOKToQjsSyFQ',
    appId: '1:642030263409:ios:1b95ac83cc14481aaacfd0',
    messagingSenderId: '642030263409',
    projectId: 'snc-customer-service',
    storageBucket: 'snc-customer-service.firebasestorage.app',
    iosBundleId: 'com.example.uiSatnetcomCustomerServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpFwRFN-XYFo3b4tnUghqMOKToQjsSyFQ',
    appId: '1:642030263409:ios:1b95ac83cc14481aaacfd0',
    messagingSenderId: '642030263409',
    projectId: 'snc-customer-service',
    storageBucket: 'snc-customer-service.firebasestorage.app',
    iosBundleId: 'com.example.uiSatnetcomCustomerServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkLlnrYJKXzgZmQy7YFAp2zOfqj80fkrM',
    appId: '1:642030263409:web:b127dd1b0054d761aacfd0',
    messagingSenderId: '642030263409',
    projectId: 'snc-customer-service',
    authDomain: 'snc-customer-service.firebaseapp.com',
    storageBucket: 'snc-customer-service.firebasestorage.app',
    measurementId: 'G-SQ0GQL2ZPJ',
  );

}